GladcherryShopping/Areas/Administrator/Controllers/QrEntitiesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer.Models;
using DataLayer.ViewModels.PagerViewModel;
using static GladCherryShopping.Helpers.FunctionsHelper;
using GladcherryShopping.Models;
using GladCherryShopping.Helpers;

namespace GladcherryShopping.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class QrEntitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Administrator/QrEntities
        public ActionResult Index(int page = 1)
        {
            var QrEntities = db.QrEntities;
            PagerViewModels<QrEntity> QrEntityViewModels = new PagerViewModels<QrEntity>();
            QrEntityViewModels.CurrentPage = page;
            QrEntityViewModels.data = QrEntities.OrderByDescending(current => current.ProductId).Skip((page - 1) * 10).Take(10).ToList();
            QrEntityViewModels.TotalItemCount = QrEntities.Count();
            return View(QrEntityViewModels);
        }

        // GET: Administrator/QrEntities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QrEntity QrEntity = db.QrEntities.Find(id);
            if (QrEntity == null)
            {
                return HttpNotFound();
            }
            return View(QrEntity);
        }

        // GET: Administrator/QrEntities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/QrEntities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,QrCode,SerialNumber,ProductId")] QrEntity QrEntity)
        {
            if (ModelState.IsValid)
            {
                Product pro = db.Products.Find(QrEntity.Id);
                if (pro == null)
                {
                    TempData["Error"] = "محصول مورد نظر یافت نشد .";
                    return RedirectToAction("Index");
                }
                db.QrEntities.Add(QrEntity);
                db.SaveChanges();
                TempData["Success"] = "کیو آر کد مورد نظر شما با موفقیت در سامانه ثبت شد .";
                return RedirectToAction("Index");
            }
            return View(QrEntity);
        }

        // GET: Administrator/QrEntities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QrEntity QrEntity = db.QrEntities.Find(id);
            if (QrEntity == null)
            {
                return HttpNotFound();
            }
            return View(QrEntity);
        }

        // POST: Administrator/QrEntities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,QrCode,SerialNumber,ProductId")] QrEntity QrEntity)
        {
            if (ModelState.IsValid)
            {
                Product pro = db.Products.Find(QrEntity.Id);
                if (pro == null)
                {
                    TempData["Error"] = "محصول مورد نظر یافت نشد .";
                    return RedirectToAction("Index");
                }
                db.Entry(QrEntity).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Success"] = "کیو آر کد مورد نظر شما با موفقیت در سامانه ویرایش شد .";
                return RedirectToAction("Index");
            }
            return View(QrEntity);
        }

        // GET: Administrator/QrEntities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QrEntity QrEntity = db.QrEntities.Find(id);
            if (QrEntity == null)
            {
                return HttpNotFound();
            }
            return View(QrEntity);
        }

        // POST: Administrator/QrEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QrEntity QrEntity = db.QrEntities.Find(id);
            db.QrEntities.Remove(QrEntity);
            try
            {
                db.SaveChanges();
            }
            catch (Exception)
            {
                TempData["Error"] = "به دلیل وجود وابستگی ها در سیستم امکان حذف این کیو آر کد وجود ندارد .";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GladcherryShopping/Areas/Administrator/Views/QrEntities/Create.cshtml
@model DataLayer.Models.QrEntity

@{
    ViewBag.Title = "افزودن کیو آر کد جدید";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت  کیو آر کد ها</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> افزودن  کیو آر کد جدید </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Create", "QrEntities", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.Label("شماره محصول", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control", @min = "1", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("لینک کیو آر کد", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.QrCode, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.QrCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("سریال نامبر", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="ذخیره اطلاعات" class="btn btn-success btn-md" />
                                    @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GladcherryShopping/Areas/Administrator/Views/QrEntities/Delete.cshtml
@model DataLayer.Models.QrEntity

@{
    ViewBag.Title = "حذف کیو آر کد";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت کیو آر کد ها</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> آیا از حذف این کیو آر کد اطمینان دارید ؟ </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div>
                        <dl class="dl-horizontal">

                            <dt>
                                شماره محصول
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ProductId)
                            </dd>

                            <dt>
                                لینک کیو آر کد
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.QrCode)
                            </dd>

                            <dt>
                                سریال نامبر
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.SerialNumber)
                            </dd>

                        </dl>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="حذف" class="btn btn-danger btn-md" /> |
                            @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GladcherryShopping/Areas/Administrator/Views/QrEntities/Details.cshtml
@model DataLayer.Models.QrEntity

@{
    ViewBag.Title = "جزییات کیو آر کد";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت دسته بندی ها</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> جزییات کیو آر کد </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div>
                        @*<h4>HubSYS Software Application 2016-2017</h4>
                            <hr />*@
                        <dl class="dl-horizontal">
                            @*<dt>
                                @Html.DisplayNameFor(model => model.Parent.PersianName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Parent.PersianName)
                            </dd>*@

                            <dt>
                                @Html.DisplayNameFor(model => model.PersianName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PersianName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.EnglishName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.EnglishName)
                            </dd>

                            @*<dt>
                                @Html.DisplayNameFor(model => model.Icon)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Icon)
                            </dd>*@

                            <dt>
                                @Html.DisplayNameFor(model => model.SmallImage)
                            </dt>

                            <dd>
                                <img src="@Model.SmallImage" class="customized_panel_table img-circle" />
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.LargeImage)
                            </dt>

                            <dd>
                                <img src="@Model.LargeImage" class="customized_panel_table img-circle" />
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.BackgroundProImage)
                            </dt>

                            <dd>
                                <img src="@Model.BackgroundProImage" class="customized_panel_table img-circle" />
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("ویرایش", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning btn-md" }) |
                        @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

GladcherryShopping/Areas/Administrator/Views/QrEntities/Edit.cshtml
@model DataLayer.Models.QrEntity

@{
    ViewBag.Title = "ویرایش اطلاعات کیو آر کد";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت کیو آر کد ها</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> ویرایش کیو آر کد </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("Edit", "QrEntities", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.Label("شماره محصول", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control", @min = "1", required = "required" } })
                                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                            </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("لینک کیو آر کد", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.QrCode, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.QrCode, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("سریال نامبر", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                    @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="ثبت تغییرات" class="btn btn-warning btn-md" />
                                    @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GladcherryShopping/Areas/Administrator/Views/QrEntities/Index.cshtml
@model DataLayer.ViewModels.PagerViewModel.PagerViewModels<DataLayer.Models.QrEntity>
@using MvcPager
@{
    ViewBag.Title = "لیست کیو آر کد ها";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت کیو آر کد ها</h2>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>لیست کیو آر کد ها</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <h4> &nbsp; &nbsp; افزودن کیو آر کد جدید &nbsp; &nbsp; <a class="btn btn-success" href="/Administrator/QrEntities/Create"> <span style="font-weight:bold;font-size:18px" class="glyphicon glyphicon-plus"></span> افزودن کیو آر کد &nbsp;</a></h4>
                    <hr />
                    <div class="ibox-content table-responsive">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>
                                        شماره محصول
                                    </th>
                                    <th>
                                        کیو آر کد
                                    </th>
                                    <th>
                                        سریال نامبر
                                    </th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.data)
                                {
                                    <tr>
                                        <td>
                                            @item.Id
                                        </td>
                                        <td>
                                            @if (item.ProductId != null)
                                            {
                                                <span>@item.ProductId</span>
                                            }
                                            else
                                            {
                                                <span style="color:darkred"> تعیین نشده </span>
                                            }
                                        </td>
                                        <td>
                                            @if (item.QrCode != null)
                                            {
                                                <span>@item.QrCode</span>
                                            }
                                            else
                                            {
                                                <span style="color:darkred"> تعیین نشده </span>
                                            }
                                        </td>
                                        <td>
                                            @if (item.SerialNumber != null)
                                            {
                                                <span>@item.SerialNumber</span>
                                            }
                                            else
                                            {
                                                <span style="color:darkred"> تعیین نشده </span>
                                            }
                                        </td>
                                        <td>
                                            @Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-xs" }) |
                                            @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
                                        </td>
                                    </tr>
                                                }
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-6" style="direction: ltr">
                                <ul class="pagination pagination-sm">
                                    <li>@Html.Pager(10, Model.CurrentPage, Model.TotalItemCount)</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>