GladcherryShopping/Areas/Administrator/Controllers/OperatorsController.cs
using DataLayer.ViewModels.PagerViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GladcherryShopping.Models;
using DataLayer.ViewModels;
using GladCherryShopping.Helpers;

namespace GladcherryShopping.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class OperatorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Administrator/Operators
        public ActionResult Index(int page = 1)
        {
            var role = db.Roles.Where(p => p.Name == "Operator").FirstOrDefault();
            IQueryable<ApplicationUser> query = db.Users.Include(current => current.State).Include(current => current.City).Where(p => p.Roles.Any(a => a.RoleId == role.Id));
            PagerViewModels<ApplicationUser> UserViewModels = new PagerViewModels<ApplicationUser>();
            UserViewModels.CurrentPage = page;
            UserViewModels.data = query.OrderByDescending(current => current.RegistrationDate).ThenByDescending(current => current.StateId).ThenByDescending(current => current.CityId).ThenByDescending(current => current.LastName).ThenByDescending(current => current.FirstName).Skip((page - 1) * 10).Take(10).ToList();
            UserViewModels.TotalItemCount = query.ToList().Count();
            return View(UserViewModels);
        }
        [HttpGet]
        public ActionResult AddOperator()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddOperator(OperatorViewModel Operator, HttpPostedFileBase image)
        {
            IdentityResult identityResult;
            IUserStore<ApplicationUser> userstore = new UserStore<ApplicationUser>(db);
            UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(userstore);
            ApplicationUser user = new ApplicationUser { UserName = Operator.Email, Email = Operator.Email, Mobile = Operator.Mobile, AddressLine = Operator.AddressLine, IsActive = Operator.IsActive, FirstName = Operator.FirstName, LastName = Operator.LastName, BirthDate = DateTime.Now, RegistrationDate = DateTime.Now, CityId = 1, StateId = 1 };
            #region FileUploading
            if (image != null && image.ContentLength > 0)
            {
                string Path = FunctionsHelper.File(FunctionsHelper.FileMode.Upload, FunctionsHelper.FileType.Image, "~/content/images/Operators/", true, image, Server);
                if (Path != string.Empty)
                {
                    user.ProfileImage = Path;
                }
            }
            #endregion FileUploading
            try
            {
                identityResult = await UserManager.CreateAsync(user, Operator.Password);
            }
            catch (Exception)
            {
                TempData["Error"] = "خطایی رخ داده است لطفا مجدد تلاش فرمایید .";
                return View();
            }

            if (identityResult.Succeeded)
            {
                UserManager.AddToRole(user.Id, "Operator");
                TempData["Success"] = "اپراتور شما با موفقیت در سیستم ثبت گردید .";
            }
            else
            {
                TempData["Error"] = "اپراتور شما قبلا در سیستم ثبت شده است .";
                return View(Operator);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> EditOperator(string id)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            IUserStore<ApplicationUser> userstore = new UserStore<ApplicationUser>(context);
            UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(userstore);
            var user = await UserManager.FindByIdAsync(id);
            ResetOperatorViewModel model = new ResetOperatorViewModel();
            //model.Email = user.Email;
            model.Mobile = user.Mobile;
            model.FirstName = user.FirstName;
            //model.Email = user.Email;
            model.AddressLine = user.AddressLine;
            //model.Password = user.PasswordHash;
            model.LastName = user.LastName;
            model.Mobile = user.Mobile;
            model.IsActive = user.IsActive;
            model.UserId = id;
            model.ProfileImage = user.ProfileImage;
            return View(model: model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditOperator(ResetOperatorViewModel model,HttpPostedFileBase image)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            IUserStore<ApplicationUser> userstore = new UserStore<ApplicationUser>(context);
            UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(userstore);
            var user = await UserManager.FindByIdAsync(model.UserId);
            //PasswordHasher hasher = new PasswordHasher();
            //var hash = hasher.HashPassword(model.Password);
            //user.PasswordHash = hash;
            ApplicationUser editedUser = user;
            //user.Email = model.Email;
            user.Mobile = model.Mobile;
            user.FirstName = model.FirstName;
            //user.Email = model.Email;
            user.AddressLine = model.AddressLine;
            //user.PasswordHash = model.Password;
            user.LastName = model.LastName;
            user.PhoneNumber = model.Mobile;
            user.IsActive = model.IsActive;

            #region FileUpdating

            if (image != null && image.ContentLength > 0)
            {
                string Path = string.Empty;

                if (user.ProfileImage == null)
                {
                    Path = FunctionsHelper.File(FunctionsHelper.FileMode.Upload, FunctionsHelper.FileType.Image, filePath: "~/content/images/Operators/", alterName: true, file: image, Server: Server);
                }
                else
                {
                    Path = FunctionsHelper.File(FunctionsHelper.FileMode.Update, FunctionsHelper.FileType.Image, filePath: user.ProfileImage, alterName: true, file: image, Server: Server);
                }

                if (Path != string.Empty)
                {
                    user.ProfileImage = Path;
                }
            }

            #endregion FileUpdating

            try
            {
                UserManager.Update(editedUser);
                context.SaveChanges();
            }
            catch (Exception)
            {
                TempData["Error"] = "خطایی رخ داده است لطفا مجدد تلاش فرمایید .";
                return View(model);
            }
            TempData["Success"] = "اطلاعات اپراتور شما با موفقیت ویرایش شد .";
            return RedirectToAction("Index");
        }

        public ActionResult SearchOperator()
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            ViewBag.ReturnUrl = "/Administrator/Operators/SearchOperator";
            return View(users);
        }

        [HttpGet]
        public ActionResult OperatorResult(string Name, string returnUrl)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var OperatorRole = context.Roles.Where(p => p.Name == "Operator").FirstOrDefault();
            var query = context.Users.Where(p => p.FirstName.Contains(Name) || p.LastName.Contains(Name)).Include(current => current.Roles);
            if (query != null)
            {
                PagerViewModels<ApplicationUser> pageviewmodel = new PagerViewModels<ApplicationUser>();
                pageviewmodel.CurrentPage = 1;
                pageviewmodel.data = query.Include(current => current.State).Include(current => current.City).ToList();
                pageviewmodel.TotalItemCount = 1;
                return View("Index", pageviewmodel);
            }
            TempData["Error"] = " متاسفانه اپراتوری با نام " + Name + " یافت نشد . ";
            return Redirect(returnUrl);
        }

        [HttpGet]
        public ActionResult DeleteOperator(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            return View(user);
        }

        [HttpGet]
        public ActionResult DeleteOperatorConfirmed(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            var ImagePath = Server.MapPath(user.ProfileImage);
            if (System.IO.File.Exists(ImagePath))
            {
                System.IO.File.Delete(ImagePath);
            }
            try
            {
                db.Users.Remove(user);
                db.SaveChanges();
            }
            catch (Exception)
            {
                TempData["Error"] = "به دلیل وجود زیر شاخه ها امکان حذف این اپراتور وجود ندارد .";
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

GladcherryShopping/Areas/Administrator/Views/Operators/AddOperator.cshtml
@model DataLayer.ViewModels.OperatorViewModel

@{
    ViewBag.Title = "افزودن اپراتور جدید";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>افزودن اپراتور جدید</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> افزودن اپراتور جدید </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("AddOperator", "Operators", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("نام کاربری (ایمیل)", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", id = "pass" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    <br />
                                    <input type="checkbox" onclick="myFunction()">  نمایش رمز عبور
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AddressLine, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.AddressLine, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.AddressLine, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ProfileImage, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    <input type="file" name="image" class="form-control" />
                                    @Html.ValidationMessageFor(model => model.ProfileImage, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="ذخیره اطلاعات" class="btn btn-success btn-md" />
                                    @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function myFunction() {
            var x = document.getElementById("pass");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }
    </script>
}

GladcherryShopping/Areas/Administrator/Views/Operators/DeleteOperator.cshtml
@model GladcherryShopping.Models.ApplicationUser

@{
    ViewBag.Title = "حذف اپراتور";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>مدیریت اپراتورها</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> آیا از حذف این اپراتور @*با نام*@ <span style="color:darkred">@* @Model.FirstName @Model.LastName*@ </span> اطمینان دارید ؟ </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div>
                        @*<h4>HubSYS Software Application 2016-2017</h4>
                            <hr />*@
                        <dl class="dl-horizontal">

                            <dt>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.FirstName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.LastName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.LastName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ProfileImage)
                            </dt>

                            <dd>
                                <img src="@Model.ProfileImage" class="customized_panel_table img-circle" />
                            </dd>

                        </dl>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            @Html.ActionLink("حذف", "DeleteOperatorConfirmed", new { id = Model.Id }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GladcherryShopping/Areas/Administrator/Views/Operators/EditOperator.cshtml
@model DataLayer.ViewModels.ResetOperatorViewModel

@{
    ViewBag.Title = "ویرایش اپراتور";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>ویرایش اپراتور</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> ویرایش اپراتور </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">گزینه 1</a>
                            </li>
                            <li>
                                <a href="#">گزینه 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("EditOperator", "Operators", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(current => current.UserId)
                        @Html.HiddenFor(current => current.ProfileImage)
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group">
                                    @Html.Label("نام کاربری (ایمیل)", htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>*@

                            <div class="form-group">
                                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AddressLine, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.AddressLine, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.AddressLine, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ProfileImage, htmlAttributes: new { @class = "control-label col-md-2 text-right" })
                                <div class="col-md-10">
                                    <input type="file" name="image" class="form-control" />
                                    @if (Model.ProfileImage != null)
                                    {
                                        <br />
                                        <img src="@Model.ProfileImage" width="100" />
                                    }
                                    @Html.ValidationMessageFor(model => model.ProfileImage, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="ذخیره اطلاعات" class="btn btn-success btn-md" />
                                    @Html.ActionLink("بازگشت به لیست", "Index", null, new { @class = "btn btn-default btn-md" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}